# Generated by Django 2.2.4 on 2020-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_ID', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
